# Generated by Django 2.1.8 on 2019-04-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190331_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default='hey.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.FloatField(),
        ),
    ]
