# Generated by Django 2.1.8 on 2019-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190414_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
