# Generated by Django 2.1.8 on 2019-04-21 02:28

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_image_url'),
    ]

    operations = [
        UnaccentExtension(),
    ]
