# Generated by Django 2.1.7 on 2019-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
