# Generated by Django 2.1.7 on 2019-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
