# Generated by Django 2.1.7 on 2019-03-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20190315_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
