# Generated by Django 2.1.8 on 2019-04-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20190419_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
    ]
