# Generated by Django 2.1.8 on 2019-04-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20190419_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
